# Generated by Django 6.0.2 on 2026-02-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='recipes/'),
        ),
    ]
